server:
 port: 7001
eureka:
  server:
    eviction-interval-timer-in-ms: 200000   #清理的间隔时间 毫秒单位（默认是60秒）
    enable-self-preservation: true # false = 关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka:7001/eureka
  instance:
    hostname: eureka

spring:
  security:
    user:
      name: admin
      password: admin