server:
  port: 6102
spring:
  application:
    name: bs-ccr-deal-okex
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: nacos-dev:8848

#feign:
#  hystrix:
#    enabled: true
#  compression:
#    request:
#      enabled: true
#      mime-types: # 可以被压缩的类型
#        - text/xml
#        - application/xml
#        - application/json
#      min-request-size: 2048 # 超过2048的字节进行压缩
