server:
  port: 8080
spring:
  application:
    name: bs-ccr-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  sentinel:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: # 可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩

ahas:
  namespace: default
  #license: f7690a9780e14e42b948aadcbb681f9e #公网使用

project:
  name: bs-ccr-consumer-ahas

