spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bs-ccr?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123zxc
    driver-class-name: com.mysql.jdbc.Driver