server:
  port: 7080

mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
spring:
  application:
    name: bs-ccr-provider-transaction
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
