server:
  port: 7080

mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
spring:
  application:
    name: bs-ccr-provider-transaction
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

open-search:
  access-key: LTAI4FipRPK3htsT54j4ahZa
  secret-key: Oz9fRDjndnfTWMlBCcw8mVkm2Z0xQV
  host: http://opensearch-cn-shenzhen.aliyuncs.com
  appName: bs_ccr_search_trade_dev
