server:
  port: 7080

mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
spring:
  application:
    name: bs-ccr-provider-transaction
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

open-search:
  access-key: b0bb8f45c84d4b4284a3685cf9bc627a
  secret-key: aXekfxEib7WFZqseg29LpxeHbMo=
  host:
  appName:
