server:
  port: 7070
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
    #开启懒加载
  #configuration:
    #lazy-loading-enabled: true #懒加载设为true
    #aggressive-lazy-loading: false #积极加载设为false
spring:
  application:
    name: bs-ccr-provider-combo
  main:
    allow-bean-definition-overriding: true

  quartz:
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    #jdbc:
    #initialize-schema: ALWAYS
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 50
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            #            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true  #当多个实例使用同一个数据库表时必须配置
    #            clusterCheckinInterval: 10000
    #            useProperties: false

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

