server:
  port: 7070
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
    #开启懒加载
  #configuration:
    #lazy-loading-enabled: true #懒加载设为true
    #aggressive-lazy-loading: false #积极加载设为false
spring:
  application:
    name: bs-ccr-provider-combo
  main:
    allow-bean-definition-overriding: true

  schedulerx2:
    # 测试环境需要配 endpoint namespace group-id  edas下只需要配group-id
    endpoint: acm.aliyun.com
    namespace: 22c16fb2-faa1-4c49-9645-38ae59c76c6d
    group-id: ec569d2f-265b-4797-9de3-026ba38bb740 #测试组id
    #group-id: alibaba-springboot-demo-group # edas环境只需要配置groupId


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

redisScriptPath: script/incrementScore.lua

