server:
  port: 7070
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
    #开启懒加载
  #configuration:
    #lazy-loading-enabled: true #懒加载设为true
    #aggressive-lazy-loading: false #积极加载设为false
spring:
  application:
    name: bs-ccr-provider-combo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password: 123zxc
        timeout: 1000ms
        lettuce:
          pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1ms
