server:
  port: 7200
mybatis:
  mapper-locations:
    classpath:mapping/*.xml,classpath:mapper/*.xml
spring:
  application:
    name: bs-ccr-provider-product-combo
  schedulerx2:
    # 测试环境需要配 endpoint namespace group-id  edas下只需要配group-id
    endpoint: acm.aliyun.com
    namespace: 04e8e05c-4b97-493b-bfd0-39eb66a9b98d
    group-id: bs-ccr-test-schedulerx #测试组id
    #group-id: alibaba-springboot-demo-group # edas环境只需要配置groupId
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848





redisScriptPath: script/incrementScore.lua