server:
  port: 7200
mybatis:
  mapper-locations:
    classpath:mapping/*.xml,classpath:mapper/*.xml
spring:
  application:
    name: bs-ccr-provider-product-combo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848