server:
  port: 8090

spring:
  application:
    name: bs-ccr-aliCloud-api-gateway
  main:
    allow-bean-definition-overriding: true

api:
  #   mock 地区id
  regionId: cn-shanghai

  #  mock api分组id
  groupId: 3cdd2ec6b01d4ee69b0652b8153e2404

  #  mock阿里云accessKeyId
  accessKeyId: LTAIrpUjXEW4piYX

  #  mock阿里云accessSecret
  accessSecret: zIt4x1FDzv9qhmGb8IUvciUVSn1LQg

  #  api是否公开
  visibility: PRIVATE

  #  后端服务返回应答的格式
  resultType: JSON

  #  API安全认证类型
  authType: APP

  #  API 支持的协议类型，可以多选，多选情况下以英文逗号隔开
  protocol: HTTP

  serviceTimeout: 1000

  serviceAddress: https://www.aliyun.com

  bodyFormat: STREAM

  #vpcConfig mock
  vpcConfig:
    vpcId: vpc-uf63m5w85eqkzoe57o1hx
    instanceId: i-uf6fzz04jbp6wqlfs6np
    name: cajr_ccr_demo
