server:
  port: 6500
spring:
  application:
    name: bs-ccr-us-mq-consumer
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error