server:
  port: 8090
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
spring:
  application:
    name: bs-ccr-provider-user-boss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

