server:
  port: 8082
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
spring:
  application:
    name: bs-ccr-provider-strategy
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123zxc
    url: jdbc:mysql://localhost:3306/bs-ccr
    driver-class-name: com.mysql.cj.jdbc.Driver