server:
  port: 8379
spring:
  application:
    name: bs-ccr-redis

  redis:
    host: redis-small-02.3qgr5x.ng.0001.usw1.cache.amazonaws.com
    port: 6379
    lettuce:
      pool:
        max-active: 32
        max-wait: 3000ms
        max-idle: 16
        min-idle: 8





