server:
  port: 6101
spring:
  application:
    name: bs-ccr-deal
  main:
    allow-bean-definition-overriding: true

#feign:
#  hystrix:
#    enabled: true
#  compression:
#    request:
#      enabled: true
#      mime-types: # 可以被压缩的类型
#        - text/xml
#        - application/xml
#        - application/json
#      min-request-size: 2048 # 超过2048的字节进行压缩
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error
feign:
  httpclient:
    connection-timeout: 30000
ribbon:
  ConnectTimeout: 20000  #毫秒    连接超时时间
  ReadTimeout: 20000     #毫秒      逻辑处理超时时间
  OkToRetryOnAllOperations: true    # 是否对所有操作都进行重试
  MaxAutoRetries: 2     # 对当前实例的最大重试次数(请求服务超时6s则会再请求一次)
  MaxAutoRetriesNextServer: 1     # 切换实例的最大重试次数(如果还失败就切换下

