server:
  port: 7060
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
spring:
  application:
    name: bs-ccr-provider-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
