server:
  port: 8099
spring:
  application:
    name: bs-ccr-redis
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  cache:
    type: redis
    redis:
      time-to-live: 200000ms
      cache-null-values: false

logging:
  level:
    cn.bosenkeji.mapper: debug

