server:
  port: 8099
spring:
  application:
    name: bs-ccr-redis
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123zxc
    timeout: 1000ms
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

logging:
  level:
    cn.bosenkeji.mapper: debug

