server:
  port: 7100
mybatis:
  mapper-locations: classpath*:mapping/*.xml
spring:
  application:
    name: bs-ccr-provider-trade-basic-data
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: nacos-dev:8848
feign:
  httpclient:
    connection-timeout: 6000
    connection-timer-repeat: 6000


#org:
#  dromara:
#    hmily:
#      serializer: kryo
#      recover-delay-time: 1  # 定时任务延迟时间
#      retry-max: 3
#      scheduled-delay: 120
#      scheduled-thread-max: 4
#      repository-support: db
#      hmily-db-config:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/bs-ccr?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
#        username: root
#        password: 123zxc