server:
  port: 7100
mybatis:
  mapper-locations: classpath*:mapping/*.xml
spring:
  application:
    name: bs-ccr-provider-trade-basic-data
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848